import type { SpaceProgram } from "./types.js";

const now = new Date().toISOString();

export const sampleSpacePrograms: SpaceProgram[] = [
  {
    id: "space-kari-sample-family",
    source: "kari_sample",
    externalId: "KARI-SAMPLE-FAMILY",
    title: "항공우주 연구협력 패밀리기업 모집 샘플",
    agency: "한국항공우주연구원",
    sourceUrl: "https://www.kari.re.kr/",
    sourceType: "public_notice",
    sourceFamily: "KARI",
    spaceCategory: "aerospace",
    relevanceScore: 86,
    dataReusePolicy: "metadata_and_short_summary",
    commercialUseAllowed: undefined,
    defenseOrDualUse: false,
    restrictedNotice: false,
    region: "전국",
    targetRegions: ["전국"],
    industries: ["항공우주", "중소기업", "중견기업", "기술사업화"],
    technologyAreas: ["항공우주", "인공위성", "발사체", "항공"],
    targetCompanyStage: "중소·중견기업",
    targetCompanyType: "법인사업자",
    supportAmountText: "패밀리기업 기술지원/협력",
    applicationEndDate: "2024-02-29",
    announcementDate: "2024-02-08",
    summary:
      "항공기, 인공위성, 우주발사체 분야 중소·중견기업의 기술애로 해결과 기술혁신 역량 제고를 위한 KARI 패밀리기업 모집 공고.",
    eligibilityText:
      "중소·중견기업 확인서 발급 가능 기업, 공동 연구개발 수행 역량 보유 기업, KARI 지원사업 참여 기업 등.",
    requiredDocuments: ["패밀리기업 가입 신청서", "정보활용 동의서", "중소·중견기업 증명서", "회사 소개자료"],
    restrictions: ["공고 마감", "세부 선정기준과 제출양식은 원문 첨부파일 확인 필요"],
    securityRequirements: [],
    participationType: "패밀리기업 모집",
    leadApplicantAllowed: "기업 신청",
    consortiumRequired: false,
    universityOrResearchPartnerRequired: false,
    rawText:
      "한국항공우주연구원 신규 패밀리기업 모집 항공기 인공위성 우주발사체 중소 중견기업 기술애로 기술혁신 기술사업화",
    attachmentUrls: [
      "https://www.kari.re.kr//kor/article/ATCL90a22172e/18077"
    ],
    status: "closed",
    lastCheckedAt: now
  },
  {
    id: "space-kasa-001",
    source: "kasa_sample",
    externalId: "KASA-SAMPLE-001",
    title: "우주기술 실용화 촉진 기업지원 사업",
    agency: "우주항공청",
    sourceUrl: "https://www.kasa.go.kr/",
    sourceType: "notice",
    sourceFamily: "KASA",
    spaceCategory: "space_commercialization",
    relevanceScore: 95,
    dataReusePolicy: "metadata_only_until_terms_reviewed",
    commercialUseAllowed: undefined,
    defenseOrDualUse: false,
    restrictedNotice: false,
    region: "전국",
    targetRegions: ["전국"],
    industries: ["우주산업", "우주기술", "딥테크"],
    technologyAreas: ["우주기술 사업화", "위성체", "탑재체", "우주부품"],
    targetCompanyStage: "창업 7년 이내 또는 중소기업",
    targetCompanyType: "법인사업자",
    supportAmountText: "최대 5억원",
    applicationEndDate: "2026-08-14",
    announcementDate: "2026-06-01",
    summary: "민간 우주기술 사업화와 시제품 제작, 실증을 지원하는 기업지원 사업.",
    eligibilityText: "우주기술을 보유하거나 우주산업 사업화를 추진하는 국내 중소기업 대상.",
    requiredDocuments: ["사업계획서", "사업자등록증", "기술개발 계획서", "최근 재무자료"],
    restrictions: ["중복수혜 제한 확인 필요", "세부 자격은 원문 공고 확인 필요"],
    securityRequirements: [],
    participationType: "기업 단독 또는 컨소시엄",
    leadApplicantAllowed: "기업 주관 가능 여부 원문 확인 필요",
    consortiumRequired: false,
    universityOrResearchPartnerRequired: false,
    rawText:
      "우주기술 실용화 기업지원 위성체 탑재체 우주부품 사업화 시제품 실증 중소기업 지원",
    attachmentUrls: [],
    status: "active",
    lastCheckedAt: now
  },
  {
    id: "space-kasi-002",
    source: "kasi_sample",
    externalId: "KASI-SAMPLE-002",
    title: "우주감시 관측자료 활용 공동연구 공모",
    agency: "한국천문연구원",
    sourceUrl: "https://www.kasi.re.kr/",
    sourceType: "notice",
    sourceFamily: "KASI",
    spaceCategory: "astronomy_space_science",
    relevanceScore: 88,
    dataReusePolicy: "metadata_only_until_terms_reviewed",
    commercialUseAllowed: undefined,
    defenseOrDualUse: false,
    restrictedNotice: false,
    region: "전국",
    targetRegions: ["전국"],
    industries: ["우주과학", "천문관측", "데이터분석"],
    technologyAreas: ["천문관측", "우주감시", "우주상황인식", "AI 위성데이터"],
    targetCompanyStage: "기업 및 연구기관",
    targetCompanyType: "기업 또는 연구기관",
    supportAmountText: "과제별 상이",
    applicationEndDate: "2026-07-31",
    announcementDate: "2026-05-20",
    summary: "천문·우주감시 관측자료를 활용하는 공동연구 및 기술협력 공모.",
    eligibilityText: "우주감시, 관측자료 분석, 우주상황인식 관련 역량 보유 기관 대상.",
    requiredDocuments: ["연구계획서", "참여기관 현황", "개인정보 및 보안 관련 서류"],
    restrictions: ["민간기업 직접지원 여부 확인 필요", "연구기관 협력 필요 가능성"],
    securityRequirements: ["관측자료 접근 조건 확인 필요"],
    participationType: "공동연구",
    leadApplicantAllowed: "연구기관 주관 가능성 높음",
    consortiumRequired: true,
    universityOrResearchPartnerRequired: true,
    rawText:
      "한국천문연구원 우주감시 우주상황인식 천문관측 관측자료 공동연구 AI 데이터분석",
    attachmentUrls: [],
    status: "active",
    lastCheckedAt: now
  },
  {
    id: "space-dapa-003",
    source: "dapa_sample",
    externalId: "DAPA-SAMPLE-003",
    title: "국방우주 감시정찰 위성 탑재체 핵심기술 과제",
    agency: "방위사업청",
    sourceUrl: "https://www.dapa.go.kr/",
    sourceType: "public_notice",
    sourceFamily: "DAPA",
    spaceCategory: "defense_space",
    relevanceScore: 92,
    dataReusePolicy: "public_metadata_only",
    commercialUseAllowed: undefined,
    defenseOrDualUse: true,
    restrictedNotice: false,
    region: "전국",
    targetRegions: ["전국"],
    industries: ["국방우주", "방산", "위성", "탑재체"],
    technologyAreas: ["감시정찰위성", "탑재체", "국방우주", "항공전자"],
    targetCompanyStage: "방산/R&D 수행 가능 기업",
    targetCompanyType: "법인사업자",
    supportAmountText: "과제별 상이",
    applicationEndDate: "2026-09-10",
    announcementDate: "2026-06-10",
    summary: "국방우주 감시정찰 위성 관련 공개 핵심기술 과제 공고.",
    eligibilityText: "국방 R&D 수행 자격, 보안요건, 방산 관련 요건 확인 필요.",
    requiredDocuments: ["제안서", "보안 관련 서류", "수행실적", "참여자격 증빙"],
    restrictions: ["보안요건 확인 필요", "수출통제 및 방산 참여자격 확인 필요"],
    securityRequirements: ["보안심사 또는 보안서약 가능성", "국방과제 참여자격 확인 필요"],
    exportControlNotes: "방산/위성 탑재체 관련 수출통제 가능성 확인 필요",
    qualificationNotes: "방산기업 또는 국방 R&D 수행실적 요구 가능성",
    participationType: "국방 R&D 과제",
    leadApplicantAllowed: "기업 주관 가능 여부 원문 확인 필요",
    consortiumRequired: true,
    universityOrResearchPartnerRequired: false,
    rawText:
      "방위사업청 국방우주 감시정찰 위성 탑재체 핵심기술 방산 보안 수출통제",
    attachmentUrls: [],
    status: "active",
    lastCheckedAt: now
  },
  {
    id: "space-molit-004",
    source: "molit_kaia_sample",
    externalId: "MOLIT-KAIA-SAMPLE-004",
    title: "UAM 항공안전 실증 인프라 기술개발 과제",
    agency: "국토교통부/국토교통과학기술진흥원",
    sourceUrl: "https://www.kaia.re.kr/",
    sourceType: "rd_notice",
    sourceFamily: "MOLIT_KAIA",
    spaceCategory: "drone_uam_adjacent",
    relevanceScore: 64,
    dataReusePolicy: "metadata_only_until_terms_reviewed",
    commercialUseAllowed: undefined,
    defenseOrDualUse: false,
    restrictedNotice: false,
    region: "전국",
    targetRegions: ["전국"],
    industries: ["항공", "UAM", "드론", "항공안전"],
    technologyAreas: ["UAM", "항공안전", "항공전자", "실증"],
    targetCompanyStage: "기업 및 컨소시엄",
    targetCompanyType: "법인사업자",
    supportAmountText: "과제별 상이",
    applicationEndDate: "2026-08-28",
    announcementDate: "2026-06-03",
    summary: "UAM 항공안전과 실증 인프라 기술개발을 지원하는 항공 인접 R&D 과제.",
    eligibilityText: "항공/UAM 관련 기술 보유 기업 또는 컨소시엄 대상.",
    requiredDocuments: ["연구개발계획서", "컨소시엄 구성 서류", "실증 계획"],
    restrictions: ["우주 핵심 분야가 아닌 항공/UAM 인접 분야"],
    securityRequirements: [],
    participationType: "컨소시엄 R&D",
    leadApplicantAllowed: "기업 주관 가능 여부 원문 확인 필요",
    consortiumRequired: true,
    universityOrResearchPartnerRequired: false,
    rawText:
      "국토교통부 KAIA UAM 항공안전 실증 항공전자 드론 항공산업 R&D",
    attachmentUrls: [],
    status: "active",
    lastCheckedAt: now
  },
  {
    id: "space-motie-005",
    source: "motie_keit_sample",
    externalId: "MOTIE-KEIT-SAMPLE-005",
    title: "항공우주 소부장 첨단제조 기술개발 사업",
    agency: "산업통상자원부/한국산업기술기획평가원",
    sourceUrl: "https://www.keit.re.kr/",
    sourceType: "rd_notice",
    sourceFamily: "MOTIE_KEIT",
    spaceCategory: "space_parts_materials",
    relevanceScore: 82,
    dataReusePolicy: "metadata_only_until_terms_reviewed",
    commercialUseAllowed: undefined,
    defenseOrDualUse: false,
    restrictedNotice: false,
    region: "전국",
    targetRegions: ["전국"],
    industries: ["항공우주", "소부장", "첨단제조"],
    technologyAreas: ["우주부품", "항공소재", "소부장", "첨단제조"],
    targetCompanyStage: "중소·중견기업",
    targetCompanyType: "법인사업자",
    supportAmountText: "최대 10억원 내외",
    applicationEndDate: "2026-09-02",
    announcementDate: "2026-06-12",
    summary: "항공우주 부품·소재·장비의 첨단제조 기술개발을 지원하는 산업 R&D 사업.",
    eligibilityText: "항공우주 소부장 제조 역량을 보유한 국내 중소·중견기업 대상.",
    requiredDocuments: ["사업계획서", "제조역량 증빙", "재무자료", "참여기관 서류"],
    restrictions: ["제조·소부장 역량 증빙 필요"],
    securityRequirements: [],
    participationType: "산업기술 R&D",
    leadApplicantAllowed: "기업 주관 가능",
    consortiumRequired: false,
    universityOrResearchPartnerRequired: false,
    rawText:
      "산업통상자원부 KEIT 항공우주 소부장 첨단제조 우주부품 항공소재 중소 중견기업",
    attachmentUrls: [],
    status: "active",
    lastCheckedAt: now
  }
];
